var Guests = ['Mukhtar', 'Kiran', 'Khalida', 'Mahnoor', 'Salman'];
var Old_guest = Guests[0];
var new_Guest = "Nusrat";
Guests[0] = new_Guest;
var invite = "Assalamualikum, I'm organizing a party of friends I wish you could join us.";
console.log(Guests[0], "!", invite);
console.log(Guests[1], "!", invite);
console.log(Guests[2], "!", invite);
console.log(Guests[3], "!", invite);
console.log(Guests[4], "!", invite);
console.log(Old_guest, "wont be able to join party.We will miss your presence.");
